### ISSUE TITLE
Plugin URL broken

### ISSUE THREAD

**Issue by bkline** [unbit/uwsgi-docs#480]
According to the [documentation](https://uwsgi-docs.readthedocs.io/en/latest/CGI.html), building the CGI plugin is performed with the following command:

```sh
curl http://uwsgi.it/install | bash -s cgi /tmp/uwsgi
```

However, that results in

```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    17    0    17    0     0     64      0 --:--:-- --:--:-- --:--:--    64
bash: line 1: Moved: command not found
```

**Comment by ag602** [comment]
Same issue. Did anyone find the fix?

**Comment by bkline** [comment]
One would hope that if they had, they would have said so here. 🙂

**Comment by akx** [comment]
The documentation is outdated. You're seeing this error because these days, that URL returns "301 Moved Permanently" to the HTTPS URL https://uwsgi.it/install, which subsequently returns a 404.

That aside, you shouldn't blindly pipe commands from the internet, especially from `http://` (c.f. `https://`) URLs into `bash` in the first place, since they can do absolutely anything to your box.

**Comment by retifrav** [comment]
As of today, documentation [still mentions](https://uwsgi-docs.readthedocs.io/en/latest/CGI.html#enabling-the-plugin) this URL:

> To build a single binary with CGI support:
>
> ```
> curl http://uwsgi.it/install | bash -s cgi /tmp/uwsgi
> ```

I see that it [was removed](https://github.com/akx/uwsgi-docs/commit/214d52675067a1c2edf89ab4c2806927fbe7b8da) from documentation source, but perhaps it was never deployed to the actual documentation website?
